CREATE TABLE SENSOR (
    ID varchar(100) NOT NULL,
    PARK int,
    INSERT_DATE timestamp,
    ENABLE tinyint(1),
    DETAILS varchar(1000),
    DEVICE_ID int,
    UPDATE_DATE timestamp
);

CREATE TABLE DATA(
    ID varchar(100) NOT NULL,
    DATA_VALUE int,
    INSERT_DATE timestamp,
    SENSOR_ID varchar(100)
);

ALTER TABLE SENSOR ADD CONSTRAINT PK_SENSOR PRIMARY KEY (ID);
ALTER TABLE DATA ADD CONSTRAINT PK_DATA PRIMARY KEY (ID);

ALTER TABLE DATA ADD CONSTRAINT FK_DATA_SENSOR FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(ID);
